import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Sparkles, Loader2, Wand2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { uploadImageToStorage } from '@/lib/storage';

interface AIImageGeneratorProps {
  initialPrompt?: string;
  context?: string; // Título o contenido del artículo para generar prompt automático
  onImageGenerated: (url: string) => void;
  trigger?: React.ReactNode;
}

const AIImageGenerator = ({ initialPrompt = '', context = '', onImageGenerated, trigger }: AIImageGeneratorProps) => {
  const [open, setOpen] = useState(false);
  const [prompt, setPrompt] = useState(initialPrompt);
  const [generating, setGenerating] = useState(false);
  const [optimizing, setOptimizing] = useState(false);
  const [status, setStatus] = useState<string>('');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Update prompt if prop changes
  useEffect(() => {
    if (initialPrompt) setPrompt(initialPrompt);
  }, [initialPrompt]);

  // Auto-generate prompt on open if empty but context exists
  useEffect(() => {
    if (open && !prompt && context && !hasAutoGenerated) {
      handleOptimizePrompt();
      setHasAutoGenerated(true);
    }
  }, [open, prompt, context]);

  const base64ToFile = (base64String: string, filename: string): File => {
    const arr = base64String.split(',');
    const bstr = atob(arr.length > 1 ? arr[1] : base64String); 
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new File([u8arr], filename, { type: 'image/png' });
  };

  const handleOptimizePrompt = async () => {
    const textBase = prompt || context;
    if (!textBase) {
      toast.error("Escribe una idea base o asegúrate de que el artículo tenga título.");
      return;
    }

    setOptimizing(true);
    try {
      const { data, error } = await supabase.functions.invoke('rewrite-text', {
        body: { text: textBase, type: 'prompt' }
      });
      if (error) throw error;
      setPrompt(data.rewrittenText);
      toast.success("Prompt optimizado con IA");
    } catch (e) {
      console.error(e);
      toast.error("Error optimizando prompt");
    } finally {
      setOptimizing(false);
    }
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast.error("El prompt no puede estar vacío");
      return;
    }
    
    setGenerating(true);
    setStatus('Conectando con Fal.ai (Flux)...');
    
    try {
      // 1. Generar imagen
      const { data, error } = await supabase.functions.invoke('generate-image', {
        body: { prompt: prompt.trim() }
      });

      if (error) throw new Error(error.message || 'Error en la función de generación');
      if (!data || !data.imageB64) throw new Error("No se recibieron datos de imagen");

      // 2. Convertir y Subir
      setStatus('Procesando y guardando...');
      const file = base64ToFile(data.imageB64, 'ai-generated.png');
      const result = await uploadImageToStorage(file, 'ai-generated');
      
      onImageGenerated(result.url);
      setOpen(false);
      toast.success("Imagen generada y guardada en biblioteca");

    } catch (error: any) {
      console.error('Error generating image:', error);
      toast.error(error.message || "Error al generar imagen");
    } finally {
      setGenerating(false);
      setStatus('');
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" className="w-full gap-2">
            <Sparkles className="h-4 w-4 text-purple-600" /> 
            Crear con IA
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Generador de Imágenes (Flux/Fal.ai)</DialogTitle>
          <DialogDescription>
            Crea imágenes fotorealistas para tus noticias. Puedes usar nombres de figuras públicas.
          </DialogDescription>
        </DialogHeader>
        
        <div className="py-4 space-y-3">
          <div className="relative">
            <Textarea 
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Describe la imagen... Ej: Andrés Manuel López Obrador en conferencia de prensa, iluminación natural, fotografía periodística..."
              className="h-32 font-medium pr-10 resize-none"
              disabled={generating || optimizing}
            />
            <Button 
              size="icon" 
              variant="ghost" 
              className="absolute right-2 bottom-2 hover:bg-purple-100 text-purple-600"
              onClick={handleOptimizePrompt}
              disabled={generating || optimizing}
              title="Mejorar Prompt con IA"
            >
              {optimizing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
            </Button>
          </div>
          
          <div className="text-xs text-muted-foreground flex justify-between">
            <span>Modelo: Flux Dev (Landscape 4:3)</span>
            <span className={prompt.length > 20 ? "text-green-600" : "text-amber-600"}>
              {prompt.length > 20 ? "Prompt detallado" : "Prompt corto (recomendado mejorar)"}
            </span>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)} disabled={generating}>
            Cancelar
          </Button>
          <Button 
            onClick={handleGenerate} 
            disabled={generating || optimizing || !prompt.trim()}
            className="bg-purple-600 hover:bg-purple-700 text-white gap-2 min-w-[140px]"
          >
            {generating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" /> 
                {status || 'Procesando...'}
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" /> Generar Imagen
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default AIImageGenerator;